version: '3.1'

services:
  springboot:
    image: dineshdockerpractice/spring-boot-mongo:6 #Here I'm getting image build number from Jenkins build Number environment variable automatically.
    restart: always # This will be ignored if we deploy in docker swarm
    environment: 
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb123
    ports:
      - 9090:8080
    depends_on:
      - mongo
    deploy:
      replicas: 3 #Creating springboot application image as 3 containers with service name as springboot.
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
    networks:
    - mongonetwork
    working_dir: /opt/app
    
  mongodb:  #This is mongodb database service creating as only 1 container with no volumes currently. 
    image: mongo  #Here image name should be equal to application host environment host name.
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb123
    restart: always
    networks:
    - mongonetwork
    
networks:
  mongonetwork:
    external: true
