version: '3.1'

services:
  springboot:
    image: dineshdockerpractice/spring-boot-mongo:latest
    restart: always # This will be ignored if we deploy in docker swarm
    environment: 
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb1234
    ports:
      - 8080:8080
    depends_on:
      - mongo
    deploy:
      replicas: 3 #Creating springboot application image as 3 containers with service name as springboot.
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
    networks:
    - mongonetwork
    working_dir: /opt/app
    
  mongodb:  
    image: mongo  #Here image name should be equal to application host environment host name.
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb1234
    restart: always
    networks:
    - mongonetwork
    
networks:
  mongonetwork:
    external: true
